name: CI

on:
  workflow_dispatch:
  push:
    branches:
      # The branch where the project source code resides
      # 项目源代码所在的分支
      - dev
      - main
    paths-ignore:
      # Changes involving the following path files will not trigger the workflow
      # 涉及以下路径文件的更改不会触发工作流
      - LICENSE
      - README-cmn_CN.md
      - README-cmn_TW.md
      - README-jyut.md
      - docs/**

  pull_request:
    branches:
      - dev
      - main
    paths-ignore:
      - LICENSE
      - README-cmn_CN.md
      - README-cmn_TW.md
      - README-jyut.md
      - docs/**

jobs:
  build:
    name: Build
    strategy:
      matrix:
        # 只保留最新的 LTS Node.js 版本
        node: [lts/*]
        # 只在 ubuntu 上构建
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm cache
        uses: actions/cache@v4 # 从 v3 更新到 v4
        with:
          path: |
            ~/.pnpm-store
            ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Install dependencies
        shell: bash
        run: |
          pnpm install --frozen-lockfile --no-verify-store-integrity

      - name: Build Extension
        run: pnpm build

      - name: Upload Chrome Extension Zip
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == 'lts/*' && github.ref_name == 'main' }}
        uses: actions/upload-artifact@v4.3.1
        with:
          name: eno-music Zip
          path: extension

      - name: Upload Firefox extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-firefox
          path: dist/firefox # 修改这里，确保路径与你的实际构建输出目录匹配
          if-no-files-found: error # 添加这行来帮助调试
