name: CI

on:
  workflow_dispatch:
  push:
    branches:
      # The branch where the project source code resides
      # 项目源代码所在的分支
      - dev
      - main
    paths-ignore:
      # Changes involving the following path files will not trigger the workflow
      # 涉及以下路径文件的更改不会触发工作流
      - LICENSE
      - README-cmn_CN.md
      - README-cmn_TW.md
      - README-jyut.md
      - docs/**

  pull_request:
    branches:
      - dev
      - main
    paths-ignore:
      - LICENSE
      - README-cmn_CN.md
      - README-cmn_TW.md
      - README-jyut.md
      - docs/**

jobs:
  build:
    name: Build
    strategy:
      matrix:
        node: [lts/*, lts/-1]
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: |
            - args: [--frozen-lockfile]

      - name: Build Extension
        run: pnpm build

      - name: Upload Chrome Extension Zip
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == 'lts/*' && github.ref_name == 'main' }}
        uses: actions/upload-artifact@v4.3.1
        with:
          name: eno-music Zip
          path: extension

      - name: Upload Firefox Extension Zip
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == 'lts/*' && github.ref_name == 'main' }}
        uses: actions/upload-artifact@v4.3.1
        with:
          name: eno-music-Firefox Zip
          path: extension-firefox
