name: Release

permissions:
  contents: write
  id-token: write
  pull-requests: write

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # 匹配类似 2.1.5 这样的版本号格式
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        run: npx release-it --ci
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
